language: csharp
sudo: true
dist: trusty
mono: none
dotnet: 2.1.403
before_install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/PowerShell/PowerShell/v6.1.0/tools/install-powershell.sh)
script:
  - ./build.ps1 -ci
branches:
  only:
    - master
    - travis
