# https://docs.microsoft.com/azure/devops/pipelines/yaml-schema

trigger:
- master

pr:
- '*'

variables:
- group: AzureKeyVault
- name: BuildNumber
  value: $[counter('buildnumber')]

jobs:
- job: Build
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-18.04
      MacOS:
        vmImage: macOS-latest
      Windows:
        vmImage: windows-2019
  pool:
    vmImage: $(vmImage)
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 2.2
    inputs:
      version: '2.2.x'
  - task: UseDotNet@2
    displayName: Install .NET Core 3.0
    inputs:
      version: '3.0.x'
      includePreviewVersions: true
  - powershell: ./build.ps1 -ci
    displayName: Run build.ps1
    env:
      KEYVAULT_CLIENT_SECRET: $(kv-access-token)
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: $(vmImage)
      testRunner: vstest
      testResultsFiles: '**/*.trx'
  - publish: 'artifacts/'
    artifact: 'Packages'
    displayName: Publish artifacts
    condition: and(success(), eq('windows-2019', variables['vmImage']))
