trigger:
  branches:
    include:
    - master
    - feature/*

variables:
- group: AzureKeyVault
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  workspace:
    clean: all
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core 2.2
    inputs:
      version: '2.2.102'
  - powershell: ./build.ps1 -ci -kv '$(kv-access-token)'
    displayName: Run build.ps1
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testRunTitle: Windows
      testResultsFormat: VSTest
      testResultsFiles: artifacts/TestResults/*.trx
  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      artifactName: packages
      pathtoPublish: $(Build.Repository.LocalPath)/artifacts/packages/

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  workspace:
    clean: all
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core 2.2
    inputs:
      version: '2.2.102'
  - script: ./build.ps1 -ci
    displayName: Run build.ps1
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testRunTitle: Linux
      testResultsFormat: VSTest
      testResultsFiles: artifacts/TestResults/*.trx
